// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulevjsvgrhzhtpeotkpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZXZqc3Zncmh6aHRwZW90a3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDE4NTIsImV4cCI6MjA1OTM3Nzg1Mn0.J0ejQJ8g1DQTO908-O06MxoDbSex3oTx_d19sKkT8ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);